{{- if and .Values.migration.enabled .Values.hub.migration.waitForFormaMigration.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "forma.hubMigrationWaitServiceAccountName" . }}
  labels:
    helm.sh/chart: {{ include "forma.chart" . }}
    app.kubernetes.io/name: {{ include "forma.hubname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hub-migration-wait
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Values.partOfOverride | default (include "forma.name" .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "forma.hubMigrationWaitServiceAccountName" . }}
  labels:
    helm.sh/chart: {{ include "forma.chart" . }}
    app.kubernetes.io/name: {{ include "forma.hubname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hub-migration-wait
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Values.partOfOverride | default (include "forma.name" .) }}
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    resourceNames:
      - {{ include "forma.migrationJobName" . }}
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "forma.hubMigrationWaitServiceAccountName" . }}
  labels:
    helm.sh/chart: {{ include "forma.chart" . }}
    app.kubernetes.io/name: {{ include "forma.hubname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hub-migration-wait
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Values.partOfOverride | default (include "forma.name" .) }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "forma.hubMigrationWaitServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "forma.hubMigrationWaitServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
