{{- if not .Values.hub.enabled }}
{{- fail "hub.enabled=false is not supported in Forma 5; Hub is mandatory." }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "forma.hubname" . }}
  labels:
    helm.sh/chart: {{ include "forma.chart" . }}
    app.kubernetes.io/name: {{ include "forma.hubname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hub
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Values.partOfOverride | default (include "forma.name" .) }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "forma.hubname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
