{{- if and .Values.hub.enabled .Values.hub.embeddings.enabled .Values.hub.embeddings.persistence.enabled (not .Values.hub.embeddings.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "forma.hubEmbeddingsName" . }}
  labels:
    helm.sh/chart: {{ include "forma.chart" . }}
    app.kubernetes.io/name: {{ include "forma.hubEmbeddingsName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hub-embeddings
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Values.partOfOverride | default (include "forma.name" .) }}
spec:
  accessModes:
    {{- toYaml .Values.hub.embeddings.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.hub.embeddings.persistence.size }}
  {{- with .Values.hub.embeddings.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
